/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Produto;
import Model.Produto;
import DAO.ProdutoDAO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author arthu
 */
public class EditarProduto extends javax.swing.JFrame {

    /**
     * Creates new form EditarProduto
     */
    public EditarProduto() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        atualizarComboBox();
        produtoComboBox.setSelectedItem(0);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ep_preco = new javax.swing.JTextField();
        ep_nome = new javax.swing.JTextField();
        ep_qnt_estoque = new javax.swing.JTextField();
        ep_qnt_max_estoque = new javax.swing.JTextField();
        ep_unidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        produtoComboBox = new javax.swing.JComboBox<>();
        btnVisualiarProduto = new javax.swing.JButton();
        ep_qnt_min_estoque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        reajusteComboBox = new javax.swing.JComboBox<>();
        ep_reajuste_percentual = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEditarProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(625, 424));

        jLabel2.setText("Quantidade máxima em estoque");

        jLabel3.setText("Nome");

        jLabel4.setText("Preco");

        jLabel5.setText("Unidade");

        jLabel7.setText("Quantidade mínima em estoque");

        jLabel6.setText("Quantidade em estoque");

        jButton1.setText("Salvar alterações");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ep_unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ep_unidadeActionPerformed(evt);
            }
        });

        jLabel8.setText("Produto");

        produtoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoComboBoxActionPerformed(evt);
            }
        });

        btnVisualiarProduto.setText("Visualizar produto");
        btnVisualiarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualiarProdutoActionPerformed(evt);
            }
        });

        ep_qnt_min_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ep_qnt_min_estoqueActionPerformed(evt);
            }
        });

        jLabel9.setText("Reajuste percentual");

        reajusteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        ep_reajuste_percentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ep_reajuste_percentualActionPerformed(evt);
            }
        });

        jLabel10.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(ep_qnt_min_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ep_unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ep_qnt_max_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ep_qnt_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ep_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ep_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(produtoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnVisualiarProduto)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(reajusteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ep_reajuste_percentual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ep_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ep_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ep_unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ep_qnt_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ep_qnt_max_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ep_qnt_min_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(reajusteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ep_reajuste_percentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(80, 80, 80)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(produtoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualiarProduto)
                .addGap(31, 31, 31))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Editar produto");

        TableEditarProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Unidade", "Quantidade em estoque", "Quantidade máxima", "Quantidade mínima"
            }
        ));
        jScrollPane1.setViewportView(TableEditarProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método para atualizar o combobox
    private void atualizarComboBox(){
        try{
            ProdutoDAO atualizarComboBox = new ProdutoDAO();
            List<Produto> produtos = atualizarComboBox.listarTodos();
            
            produtoComboBox.removeAllItems();
            
            //Deixar um espaço vazio no meu combobox para forçar o usuário a selecionar alguma coisa e não alterar um produto acidentalmente
            Produto placeholder = new Produto();
            placeholder.setIdProduto(0);
            placeholder.setNome("Selecione um produto.");
            produtoComboBox.addItem(placeholder);
            
            
            for (Produto p : produtos){
                produtoComboBox.addItem(p);
            }
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro: "+ex.getMessage());
        }
    }
    
    //Método visualizar na tabela
    /**
    private void mostrarTabela(){
        try{
            ProdutoDAO mostrarTabela = new ProdutoDAO();
            List<Produto> produtos = mostrarTabela.buscarPorId();
            produtoComboBox.removeAllItems();
            for (Produto p : produtos){
                produtoComboBox.addItem(p.getNome());
            }
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Erro: "+ex.getMessage());
        }
    }
    **/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Produto editarProduto = new Produto();
            
            Produto selecionado = (Produto) produtoComboBox.getSelectedItem();
            ProdutoDAO dao = new ProdutoDAO();
            
            boolean aplicouReajuste = false;
            
            double precoOriginalBanco = selecionado.getPreco(); 
            double precoDigitado = Double.parseDouble(ep_preco.getText()); 
            

            //Reajuste percentual
            if (!ep_reajuste_percentual.getText().trim().isEmpty()) { 
                try {
                    double percentual = Double.parseDouble(ep_reajuste_percentual.getText());
                    
                    
                    if (reajusteComboBox.getSelectedItem().toString().equals("-")) {
                        percentual *= -1;
                    }
                                        
                    boolean reajusteFeito = dao.reajustarPrecoProduto(selecionado, percentual);
                    
                    if (reajusteFeito) {
                        aplicouReajuste = true;
                        double novoPreco = precoDigitado * (1 + percentual / 100);
                        
                        ep_preco.setText(String.valueOf(novoPreco));
                        editarProduto.setPreco(novoPreco);
                        System.out.println("Novo preço calculado: " + novoPreco);
                        
                        if (precoDigitado != precoOriginalBanco){
                            JOptionPane.showMessageDialog(null, String.format("Você alterou o preço manualmente e aplicou um reajuste de %.2f%%.\n\n" + "Preço digitado: R$ %.2f \n" + "Novo preço com reajuste: %.2f", percentual, precoDigitado, novoPreco));
                        }
                        
                    } else {
                        System.out.println("Reajuste falhou.");
                    }
                }catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Valor de reajuste inválido.");
                }
            }if (!aplicouReajuste){
                editarProduto.setPreco(precoDigitado);
            }
            
            editarProduto.setNome(ep_nome.getText());
            editarProduto.setPreco(Double.parseDouble(ep_preco.getText()));
            editarProduto.setUnidade(ep_unidade.getText());
            editarProduto.setQuantidadeEstoque(Integer.parseInt(ep_qnt_estoque.getText()));
            editarProduto.setQuantidadeMinEstoque(Integer.parseInt(ep_qnt_min_estoque.getText()));
            editarProduto.setQuantidadeMaxEstoque(Integer.parseInt(ep_qnt_max_estoque.getText()));
           editarProduto.setIdProduto(selecionado.getIdProduto()); //w

            boolean sucesso = dao.atualizar(editarProduto);
            if (sucesso){
                JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!");
                atualizarComboBox();
                //Limpar os campos
                ep_nome.setText("");
                ep_preco.setText("");
                ep_unidade.setText("");
                ep_qnt_estoque.setText("");
                ep_qnt_min_estoque.setText("");
                ep_qnt_max_estoque.setText("");
                produtoComboBox.setSelectedItem(0);
                ep_reajuste_percentual.setText("");
                reajusteComboBox.setSelectedItem(0);

            }else{
                JOptionPane.showMessageDialog(null, "Erro ao atualizar o produto!");
            }        
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Erro com os valores númericos.");

        } catch (HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
           
 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void ep_unidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ep_unidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ep_unidadeActionPerformed

    private void btnVisualiarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualiarProdutoActionPerformed

        try {
            Produto produtoSelecionado = (Produto) produtoComboBox.getSelectedItem();
            ProdutoDAO dao = new ProdutoDAO();

            Produto produtoCompleto = dao.buscarPorId(produtoSelecionado.getIdProduto());
            
            if (produtoSelecionado.getIdProduto() == 0) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um produto válido.");
                return;
            }            

            if (produtoCompleto != null) {
                ep_nome.setText(produtoCompleto.getNome());
                ep_preco.setText(String.valueOf(produtoCompleto.getPreco()));
                ep_unidade.setText(produtoCompleto.getUnidade());
                ep_qnt_estoque.setText(String.valueOf(produtoCompleto.getQuantidadeEstoque()));
                ep_qnt_min_estoque.setText(String.valueOf(produtoCompleto.getQuantidadeMinEstoque()));
                ep_qnt_max_estoque.setText(String.valueOf(produtoCompleto.getQuantidadeMaxEstoque()));
                
            }else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnVisualiarProdutoActionPerformed

    private void produtoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoComboBoxActionPerformed

    private void ep_qnt_min_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ep_qnt_min_estoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ep_qnt_min_estoqueActionPerformed

    private void ep_reajuste_percentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ep_reajuste_percentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ep_reajuste_percentualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableEditarProduto;
    private javax.swing.JButton btnVisualiarProduto;
    private javax.swing.JTextField ep_nome;
    private javax.swing.JTextField ep_preco;
    private javax.swing.JTextField ep_qnt_estoque;
    private javax.swing.JTextField ep_qnt_max_estoque;
    private javax.swing.JTextField ep_qnt_min_estoque;
    private javax.swing.JTextField ep_reajuste_percentual;
    private javax.swing.JTextField ep_unidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Model.Produto> produtoComboBox;
    private javax.swing.JComboBox<String> reajusteComboBox;
    // End of variables declaration//GEN-END:variables
}
